---
- name: "My first play"
  hosts: k8s

  tasks:
  - name: "Test reachability"
    ansible.builtin.ping:

  - name: "Add Docker Repo"
    ansible.builtin.get_url: 
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    
  - name: "Install Docker"
    ansible.builtin.yum:
      name: docker-ce
      state: latest

  - name: "Enable and start Docker Daemon"
    ansible.builtin.systemd:
      name: docker
      enabled: yes
      state: started

  - name: "Create Docker Usergroup"
    ansible.builtin.group:
      name: docker
      state: present
